### ISSUE TITLE
Slow converge 

### ISSUE THREAD

**Issue by Ning0Luo** [MadryLab/adversarial_spatial#1]
Hi, I ran the code in my PC  with dataset provided in cifar10_challenge. It seems very slow: after  10700 steps:  training nat accuracy achieve 82.03% and training adv accuracy 75.78%. Moreover, it takes nearly 24 hours to run 10700 steps. 

I am not sure if this is quite normal or if I ran it properly.

**Comment by dtsip** [comment]
Are you running the code on a GPU?
